### PR TITLE
Add buffered combinedoutput

### PR DESCRIPTION
**Pull request by jwomackgsa**
Additional feature that allows the buffered output to have stdout and stderr combined into the same buffer which provides a capability to easily dump the buffered output to a log file.

### CODE REVIEW

**Comment by jwomackgsa** [comment]
I am still interested in this being added into the project.  I brought my fork into sync with the recent updates and should merge cleanly if accepted.  I welcome any comments.

**Comment by ip-rw** [comment]
I would like this to be merged too...

**Comment by MXWXZ** [comment]
+1 respect, useful feature

**Comment by daniel-nichter** [comment]
Sorry for long delay. Free open source software moves very slowly at times.

The feature idea is good, but let's fix two things:

1. s/BufferedCombined/CombinedOutput/ for two reasons. It mirrors Go os.Exec, and later we should extend the functionality to streaming output, too. For now, we can document that Option.CombinedOutput only works for buffered.
2. Test coverage is missing on,

```go
        case c.stdoutBuf != nil && c.stderrBuf == nil: // buffer combining stderr into stdout
                cmd.Stdout = c.stdoutBuf
                cmd.Stderr = c.stdoutBuf
```
I'm not sure why because you've got a test case, but it seems the test case doesn't actually hit that code.

**Comment by jwomackgsa** [comment]
I have updated my branch with the option name update and the additional coverage test.  Coverage is now reporting 100%.  Please let me know if anything further is needed to merge this feature.

**Comment by daniel-nichter** [comment]
Ack, thanks @jwomackgsa. I'll take a look this weekend.

**Review by daniel-nichter — APPROVED** [review]

**Pull request merged**
