### PR TITLE
Add basic windows support

### PR DESCRIPTION
**Pull request by hfrappier**

### CODE REVIEW

**Comment by daniel-nichter** [comment]
Very nice, thank you. This kind of minimal change gives me more confidence that existing functionality won't break.

I'm not familiar with Windows, but #22 handles process termination like this:
```go
	p, err := os.FindProcess(-c.status.PID)
	if err != nil {
		return err
	}
 	return p.Signal(syscall.SIGTERM)
```
That seems more native Go than `kill := exec.Command("TASKKILL", "/T", "/F", "/PID", fmt.Sprintf("%d", pid))`. Does the #22 approach work instead?

**Comment by scbizu** [comment]
Hi there, thanks to review my PR at #22 , I think it's better to add the  PLATFORM CI such as [goreleaser](https://github.com/goreleaser/goreleaser) to check if `cmd` will work as expected in other platform.

**Comment by hfrappier** [comment]
I can test this codepath when I get my hands on a windows machine.

Otherwise, as far as taskkill's doc goes,
Taskkill is the equivalent of SIGTERM
Taskkill /T handles child processes,
Taskkill /F is the equivalent of SIGKILL

**Comment by nyanshak** [comment]
What else needs to happen to get this merged? Anything I can do?

**Comment by daniel-nichter** [comment]
Sticking point is `kill := exec.Command("TASKKILL", "/T", "/F", "/PID", fmt.Sprintf("%d", pid))`. I don't think it's a good idea to exec another program like that. I'm not a Windows expert, but if it were Linux my concern would be that `TASKKILL` isn't in `$PATH` or even installed. I suspect the same would hold true for Windows, making that approach too fragile.

Instead, a native Go solution like #22 is preferable. I presume that's same as `TASKKILL`? If so, just replace the Windows implementation in this PR with #22 's implementation.

**Comment by nengc** [comment]
"TASKKILL" is the most credible method to kill the process after trying any possible methods.

**Comment by hfrappier** [comment]
[gopsutil](https://github.com/shirou/gopsutil/blob/master/process/process_windows.go)
uses:
`process := os.Process{Pid: int(p.Pid)}
	return process.Kill()
`

**Comment by daniel-nichter** [comment]
Thanks @hfrappier, I'll merge this and switch the Windows implementation to use `os.Process`. I think it's best to rely on Go's built-in process management rather than shell out to another process (TASKKILL).

**Comment by scbizu** [comment]
May I ask that why not use `os.FindProcess` directly ? 

( As [Go doc mentioned](https://golang.org/pkg/os/#FindProcess) , Windows will return an error if we have some unexpected case ? )

The `err` which returned by `os.FindProcess` will be ignored in current  implementation ?

**Pull request merged**
